version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - mynetwork

  backend:
    build: ./backend
    container_name: backend
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


